steps:
- label: ":ballot_box_with_ballot:"
  command: "echo this yml exist only in feature-x branch for testing purpose"
  command: ./src/generate-and-store-number.sh

- wait

- block: ":incoming_envelope: generate"
  prompt: "Should we generate some numbers?"
- label: ":pipeline:"
  command: ./src/generate-steps-from-stored-number.sh | buildkite-agent pipeline upload

- wait

- label: ":desktop_computer:"
  command: ./src/fetch-and-display-number.sh collect
